default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= Rails.application.credentials.dig(:database, :url) %>

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] || Rails.application.credentials.dig(:database, :url) %>